### ISSUE TITLE
Inclusion of mczify into Coq platform 8.12.0

### ISSUE THREAD

**Issue by MSoegtropIMC** [math-comp/mczify#12] opened 2020-07-26 14:13 UTC
Maybe you are aware of the Coq platform project - if not please have a look at : (https://github.com/MSoegtropIMC/coq-platform/blob/master/charter.md)

I and others would appreciate to include mczify into the Coq platform. Are you OK with that? If you say yes you also agree to put reasonable effort into maintaining mczify in the future for new Coq releases. If you would like to see mczify included, please create an issue at the above coq-platform repo. For 8.12 there is nothing else to do - I can take care of e.g. an opam package.

**Comment by gares** [comment] 2020-11-06 12:23
@pi8027 are you OK with this?

**Comment by pi8027** [comment] 2020-12-16 01:59
@MSoegtropIMC Sorry for the late response. Since mczify has less functionalities with Coq 8.12 and I do not have much time to work on improvements, I would like to include it only from Coq platform 8.13. Does it work for you?

**Comment by MSoegtropIMC** [comment] 2020-12-16 08:47
Just in time - I am anyway only about to start to add additional modules to the Coq platform. It is perfectly OK to add this for 8.13 onwards - the platform for 8.13 will likely be released short after the one for 8.12 since it took us so long to fix all the initial issues. What is most important is that the functionality which exists in 8.13 is maintained and supported in future Coq platforms.

**Comment by pi8027** [comment] 2020-12-16 11:29
Good! I think we have to set up an extensive test suite to make sure we will not introduce any regression. For packaging, I would like to discuss versioning conventions -- IMO, version numbers of `mczify` should be taken from ones of MathComp (and optionally Coq), e.g., `mczify-1.12-8.13` which is compatible with MathComp 1.12 and Coq 8.13, since what we can do in `mczify` are mostly depending on functionalities provided by Coq and MathComp (this one seems related to #11). I will open new issues for them.

**Comment by MSoegtropIMC** [comment] 2020-12-16 12:00
We discussed a while back if it is possible to factor out the Coq and mathcomp dependent parts, so that any combination of supported mathcomp and Coq versions would work. Did you find this doable or difficult? Technically I guess this wold mean that you have 3 opam packages, one which tracks the mathcomp version, one which tracks the Coq version, and one which is compatible with certain version ranges of these two packages.

In case this is not possible, since mczify depends heavily on both, mathcomp and zify, it would indeed make sense to have such a double version number. It is a difficult question which one you would like to put first, so that the version comparison algorithms do what you want. I would think that it would be better to put the Coq version first, but I am not sure. @gares, @palmskog: what do you think? Also note that hyphens are a top level separator in opam version numbers, which might have some unexpected effects. But your usage looks fine as long as you always use the same format / number of hyphens.

**Comment by palmskog** [comment] 2020-12-16 12:28
The convention used for version names that are tied to a Coq release used in the Coq opam archive are typically as follows:
```
coq-<package-name>.<package-version>+<coq-version>
```
So from what @pi8027 is suggesting it might be:
```
coq-mathcomp-zify.1.12+8.13
```
To be even more fancy and account for possible bugfixes, I would go with:
```
coq-mathcomp-zify.1.12.0+8.13
```

**Comment by gares** [comment] 2020-12-16 14:01
I think `1.12` is the version of mathcomp, not the version of mczify, so the choice would be, I guess, between:
```
coq-mathcomp-zify.1.0.0+1.12+8.13
coq-mathcomp-zify.1.0.0+8.13+1.12
```
I think I prefer the second, *but* I also thing it is a bad idea to "glue" the version of the dependencies together with the version of the software. It's the opam metadata that contains the dependencies, encoding them in is ok but not necessary IMO.

What I personally do with Coq-Elpi is to pick a version I like for my software, and only increment the minor number when I adapt it to Coq. E.g. Coq-Elpi 1.8.0 depends on Coq 8.12 and 1.8.1 on Coq 8.13. By depending on Coq-Elpi 1.8.x you say you need the features of the 1.8.x series (which I commit to keep the same, if add some then I bump the second number, or the first one if I break many many APIs).

**Comment by MSoegtropIMC** [comment] 2020-12-16 14:58
I guess the issue here is that mczify depends heavily on zify - which is part of the Coq standard library - and mathcomp and as far as I understand one needs to create a specific version of mczify for each *combination*. So connecting versions of mczify with ranges of versions of Coq and mathcomp will not work - unless one can factor mczify somehow.

**Comment by palmskog** [comment] 2020-12-16 15:15
My recommendation of `coq-mathcomp-zify.1.12.0+8.13` is indeed based on the fact that mczify is very tightly coupled to both Coq and the MathComp version, so I don't think it makes sense to have an additional version number like 1.0.0.

**Comment by gares** [comment] 2020-12-16 17:13
I see that, but if you need to release a fix on top of `coq-mathcomp-zify.1.12.0+8.13`, how do you call it?

**Comment by palmskog** [comment] 2020-12-16 17:24
> I see that, but if you need to release a fix on top of `coq-mathcomp-zify.1.12.0+8.13`, how do you call it?

Analogously to what we use in coq-community, you could call it `coq-mathcomp-zify.1.12.1+8.13`.

**Comment by gares** [comment] 2020-12-16 17:38
I see, you would "inherit" the version number from mathcomp, but it would become proper to mczify. Looks a bit fishy if MC ever releases 1.12.1 itself, but well, you may live with that.

**Comment by pi8027** [comment] 2020-12-18 08:10
> We discussed a while back if it is possible to factor out the Coq and mathcomp dependent parts, so that any combination of supported mathcomp and Coq versions would work. Did you find this doable or difficult? Technically I guess this wold mean that you have 3 opam packages, one which tracks the mathcomp version, one which tracks the Coq version, and one which is compatible with certain version ranges of these two packages.

@MSoegtropIMC Yes, I think that is doable (and that is the topic of #11). But, I have nothing to do with this currently since it is difficult to support both Coq 8.12 and 8.13 in the same branch of mczify (the ways they support boolean predicates are different) and 1.12 is the only released version of MathComp compatible with Coq 8.13. Anyway, if we will support certain versions of Coq and MathComp in one master branch of mczify that way, I think its version names should be, as suggested by @gares, e.g.,
```
coq-mathcomp-zify.1.0.0+1.12+8.13
```
Since extending mczify according to the changes of Coq (e.g., supporting rational numbers, arbitrary `realFieldType`, or a more general structure) is less likely to happen, I prefer this ordering: `<mczify-version>+<mathcomp-version>+<coq-version>`.

BTW, I managed make the `zify` instances for `coq-mathcomp-ssreflect` independent from `coq-mathcomp-algbera`. So now we can package these two parts separately (`coq-mathcomp-zify-ssreflect` and `coq-mathcomp-zify-algebra`?). IIRC, this was a request from @palmskog or Emilio. I will open a PR about this.

**Comment by MSoegtropIMC** [comment] 2020-12-18 08:37
In general I am more interested in the future than in the past. If Coq 8.12 is especially difficult to support in a more abstracted way, I think it would be better to do something which is design wise looking into the future.

**Comment by MSoegtropIMC** [comment] 2021-09-25 11:08
I am working on a new Coq Platform release and wanted to recap the status.

I see that there is an opam package version `1.0.0+1.12+8.13`, so I guess the technical issues with maintenance we discussed above are solved now. Do you plan a release for 8.14 soon?

Do you agree to include mczify into the full maintained part of Coq Platform according the the [charter](https://github.com/coq/platform/blob/2021.02/charter.md)?

**Comment by gares** [comment] 2021-09-25 14:52
@pi8027 IIRC coq-mathcomp-zify is a dependency of coq-mathcomp-algebra-tactics (providing ring and field on mathcomp). It would be nice to have both in the platform (at some point)!

**Comment by pi8027** [comment] 2021-09-27 10:40
Hi. I agree to include mczify into the full maintained part of the Coq platform according to the charter. (BTW, it would be nice if someone will co-maintain mczify.)

AFAIK, Coq 8.14 does not introduce any compatibility-breaking change in Micromega, and mczify 1.0.0+1.12+8.13 is already compatible with Coq 8.14. I think that we can interpret this version numbering like "mczify version 1.0.0, compatible with MathComp 1.12, Coq 8.13, **and their few later versions**". So, is it fine to include mczify 1.0.0+1.12+8.13 (or 1.1.0+1.12+8.13 if I will release it) into a Coq release compatible with Coq 8.14?

**Comment by pi8027** [comment] 2021-10-01 07:21
IIUC, all the issues here have been addressed. So now I can close this issue.

**Closed by pi8027** 2021-10-01 07:21 UTC

**Comment by MSoegtropIMC** [comment] 2021-10-01 07:31
Yes, all is set for 2021.09 8.13 and 8.14+beta. For 2021.11 8.14 I will ask for your plans some time soon.

Thanks for your support of the Coq Platform project!
